# adf-cicd.yml
name: Azure Data Factory CICD

# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the "main" branch
  push:
    branches: [ "main" ]
    paths-ignore:
      - '**.md'
      - '**.sqlproj'
      - '**.xml'
      - '**/.github/workflows/**'
  workflow_dispatch:

env:
  ResourceGroup: rg-adfdevops-demo

permissions:
      id-token: write
      contents: read
  
jobs:
  
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: STEP 1 Check out repository
        uses: actions/checkout@v3
        
      - name: STEP 2 Export ARM Template
        id: export
        uses: Azure/data-factory-export-action@v1.0.2
        
      # Uploading our artifact from adf_publish branch
      - name: STEP 3 Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: adf-artifact
          path: ${{ steps.export.outputs.arm-template-directory }}
          
  SIT_Deploy:
    runs-on: ubuntu-latest
    needs: build
    environment: SIT
    steps:
    
      # Downloading the artifact we uploaded earlier
      - name: STEP 4 Download a Build Artifact
        uses: actions/download-artifact@v3.0.0
        with:
          # Artifact name
          name: adf-artifact
          
      # Logging in to Azure with OIDC
#      - name: STEP 5 Az CLI login
#        uses: azure/login@v1
#        with:
#           client-id: ${{ secrets.AZURE_CLIENT_ID }}
#           tenant-id: ${{ secrets.AZURE_TENANT_ID }}
#           subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
#           enable-AzPSSession: true 

      # Logging in to Azure with Azure Key Vault
      - name: STEP 5 Az CLI login (Azure Key Vault)
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - uses: Azure/get-keyvault-secrets@v1
        with: 
          keyvault: "ads-keyvault-kam"
          secrets: 'clientID, tenantID, subscriptionID'
        id: myGetSecretAction
          
      # Deploying to SIT environment
      - name: STEP 6 Deploy resources to SIT
        uses: Azure/data-factory-deploy-action@v1.2.0
        with:
          resourceGroupName: ${{ env.ResourceGroup }}
          dataFactoryName: ADF-KMCICDDemo-SIT
          armTemplateFile: ARMTemplateForFactory.json

  UAT_Deploy:
    runs-on: ubuntu-latest
    needs: SIT_Deploy
    environment: UAT
    steps:
    
      # Downloading the artifact we uploaded earlier
      - name: STEP 7 Download a Build Artifact
        uses: actions/download-artifact@v3.0.0
        with:
          # Artifact name
          name: adf-artifact
      
      # Logging in to Azure with OIDC
#      - name: STEP 5 Az CLI login
#        uses: azure/login@v1
#        with:
#           client-id: ${{ secrets.AZURE_CLIENT_ID }}
#           tenant-id: ${{ secrets.AZURE_TENANT_ID }}
#           subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
#           enable-AzPSSession: true 

      # Logging in to Azure with Azure Key Vault
      - name: STEP 5 Az CLI login (Azure Key Vault)
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - uses: Azure/get-keyvault-secrets@v1
        with: 
          keyvault: "ads-keyvault-kam"
          secrets: 'clientID, tenantID, subscriptionID'
        id: myGetSecretAction
          
      # Deploying to UAT environment
      - name: STEP 9 Deploy resources to UAT
        uses: Azure/data-factory-deploy-action@v1.2.0
        with:
          resourceGroupName: ${{ env.ResourceGroup }}
          dataFactoryName: ADF-KMCICDDemo-UAT
          armTemplateFile: ARMTemplateForFactory.json

  PROD_Deploy:
    runs-on: ubuntu-latest
    needs: UAT_Deploy
    environment: PROD
    steps:
    
      # Downloading the artifact we uploaded earlier
      - name: STEP 10 Download a Build Artifact
        uses: actions/download-artifact@v3.0.0
        with:
          # Artifact name
          name: adf-artifact
          
      # Logging in to Azure with OIDC
#      - name: STEP 5 Az CLI login
#        uses: azure/login@v1
#        with:
#           client-id: ${{ secrets.AZURE_CLIENT_ID }}
#           tenant-id: ${{ secrets.AZURE_TENANT_ID }}
#           subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
#           enable-AzPSSession: true 

      # Logging in to Azure with Azure Key Vault
      - name: STEP 5 Az CLI login (Azure Key Vault)
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - uses: Azure/get-keyvault-secrets@v1
        with: 
          keyvault: "ads-keyvault-kam"
          secrets: 'clientID, tenantID, subscriptionID'
        id: myGetSecretAction
          
      # Deploying to PROD environment
      - name: STEP 12 Deploy resources to PROD
        uses: Azure/data-factory-deploy-action@v1.2.0
        with:
          resourceGroupName: ${{ env.ResourceGroup }}
          dataFactoryName: ADF-KMCICDDemo-PROD
          armTemplateFile: ARMTemplateForFactory.json
