# .github/workflows/ah2-sql-deploy.yml
name: AH2 SQL CI/CD Pipeline

on: 
  push:
  workflow_dispatch:

permissions:
      id-token: write
      contents: read
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    
    - run: dotnet build /p:NetCoreBuild=true /p:OutputPath=./Output ./DatabaseProjectADFCICD.sqlproj
    
    - uses: actions/upload-artifact@v3
      with:
          name: dacpac-artifact
          path: ./Output
          
  SIT_Deploy:
    runs-on: ubuntu-latest
    needs: build
    environment: SIT
    steps:
    
      # Downloading the artifact we uploaded earlier
      - name: Download a Build Artifact
        uses: actions/download-artifact@v3.0.0
        with:
          # Artifact name
          name: dacpac-artifact

      # Logging in to Azure with OIDC
      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true 
          
      - uses: azure/sql-action@v1.3
        with:
          connection-string: ${{ secrets.AZURE_SQL_CONNECTION_STRING }}
          dacpac-package: './DatabaseProjectADFCICD.dacpac'
          arguments: '/p:DropObjectsNotInSource=true'   # Optional parameters for SqlPackage Publish
          
  UAT_Deploy:
    runs-on: ubuntu-latest
    needs: SIT_Deploy
    environment: UAT
    steps:
    
      # Downloading the artifact we uploaded earlier
      - name: Download a Build Artifact
        uses: actions/download-artifact@v3.0.0
        with:
          # Artifact name
          name: dacpac-artifact
          
      - uses: azure/sql-action@v1.3
        with:
          connection-string: ${{ secrets.AZURE_SQL_CONNECTION_STRING }}
          dacpac-package: './DatabaseProjectADFCICD.dacpac'
          arguments: '/p:DropObjectsNotInSource=true'   # Optional parameters for SqlPackage Publish
          
  Prod_Deploy:
    runs-on: ubuntu-latest
    needs: UAT_Deploy
    environment: Prod
    steps:
    
      # Downloading the artifact we uploaded earlier
      - name: Download a Build Artifact
        uses: actions/download-artifact@v3.0.0
        with:
          # Artifact name
          name: dacpac-artifact
          
      - uses: azure/sql-action@v1.3
        with:
          connection-string: ${{ secrets.AZURE_SQL_CONNECTION_STRING }}
          dacpac-package: './DatabaseProjectADFCICD.dacpac'
          arguments: '/p:DropObjectsNotInSource=true'   # Optional parameters for SqlPackage Publish
