# .github/workflows/sql-deploy.yml
name: SQL CICD

on: 
  push:
      paths:
      - '**.sqlproj'
      - '**/dbo/**'
      - '**/SalesLT/**'
      - '**/Security/**'
  workflow_dispatch:

env:
  ResourceGroup: rg-adfdevops-demo

permissions:
      id-token: write
      contents: read
 
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
  SIT_Deploy:
    runs-on: ubuntu-latest
    needs: build
    environment: SIT
    steps:

    # Logging in to Azure with OIDC
    - name: 'Az CLI login'
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        enable-AzPSSession: true 
 
    - uses: azure/sql-action@v2
      with:        
        connection-string: ${{ secrets.AZURE_SQL_CONNECTION_STRING }}
        path: './DatabaseProjectADFCICD.sqlproj'
        action: 'publish'
        build-arguments: '-c Release'                 # Optional build options passed to dotnet build
        arguments: '/p:DropObjectsNotInSource=true'   # Optional properties and parameters for SqlPackage Publish
