# .github/workflows/sql-deploy.yml
name: SQL CICD

on: 
  push:
      paths:
      - '**.sqlproj'
      - '**/dbo/**'
      - '**/SalesLT/**'
      - '**/Security/**'
  workflow_dispatch:

jobs:
  SIT_Deploy:
    runs-on: ubuntu-latest
    environment: SIT
    steps:
    - uses: actions/checkout@v1
    - uses: azure/login@v1                            # Azure login required to add a temporary firewall rule
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - uses: azure/sql-action@v2
      with:        
        connection-string: ${{ secrets.AZURE_SQL_CONNECTION_STRING }}
        path: './DatabaseProjectADFCICD.sqlproj'
        action: 'publish'
        build-arguments: '-c Release'                 # Optional build options passed to dotnet build
        arguments: '/p:DropObjectsNotInSource=true'   # Optional properties and parameters for SqlPackage Publish
