# .github/workflows/working-sql-cicd.yml
name: WORKING Azure SQL CICD

#Sets the trigger to update when update is pushed to main branch
on:
  push:
    branches: 
      - main
    paths:
      - '**.sqlproj'
      - '**/dbo/**'
      - '**/SalesLT/**'
      - '**/Security/**'
  workflow_dispatch:

env:
  ResourceGroup: rg-adfdevops-demo

permissions:
      id-token: write
      contents: read

jobs:

  # Job to build and publish the dacpac
  build:
    # Easier to use Github-hosted runner if updating in GitHub
    runs-on: windows-2019
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:                                                                    
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: STEP 1 Check out repository                                                                                                                                            
        uses: actions/checkout@v2.3.4
      # Find msbuild                                      
      - name: STEP 2 Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1
      # create dacpac using MSBUILD
      - name: STEP 3 Build Database project
        run: |
          msbuild.exe DatabaseProjectADFCICD.sqlproj /p:Configuration=Release
      # Publish artifact
      - name: STEP 4 Publish artifact
        uses: actions/upload-artifact@v3.0.0
        with:
          name: DatabaseProjectADFCICD
          path: ${{ github.workspace }}/bin/Release/ 

  download-artifact:
    needs: build
    environment: SIT
    runs-on: windows-latest

    # Steps to deploy the updates to Azure SQL Database
    steps:
      - name: STEP 5 download artifact containing dacpac
        # Dowloads Data artifact to dacpac folder
        uses: actions/download-artifact@v3.0.0
        with:
          name: DatabaseProjectADFCICD

  deploy-to-sit:
    needs: download-artifact
    environment: SIT
    runs-on: ubuntu-latest

    # Steps to deploy the updates to Azure SQL Database
    steps:
      - name: STEP 6 Azure SQL Deploy
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - uses: Azure/sql-action@v2
        with:
          connection-string: ${{ secrets.AZURE_SQL_CONNECTION_STRING }}
          path: './DatabaseProjectADFCICD.dacpac'
          action: 'publish'

  deploy-to-uat:
    needs: deploy-to-sit
    environment: UAT
    runs-on: ubuntu-latest

    # Steps to deploy the updates to Azure SQL Database
    steps:
      - name: STEP 7 Azure SQL Deploy
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - uses: Azure/sql-action@v2
        with:
          connection-string: ${{ secrets.AZURE_SQL_CONNECTION_STRING }}
          path: './DatabaseProjectADFCICD.dacpac'
          action: 'publish'

  deploy-to-prod:
    needs: deploy-to-uat
    environment: PROD
    runs-on: ubuntu-latest

    # Steps to deploy the updates to Azure SQL Database
    steps:
      - name: STEP 8 Azure SQL Deploy
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - uses: Azure/sql-action@v2
        with:
          connection-string: ${{ secrets.AZURE_SQL_CONNECTION_STRING }}
          path: './DatabaseProjectADFCICD.dacpac'
          action: 'publish'
